resolver: nightly-2019-05-25

packages:
  - '.'

extra-deps:
  - git:     https://github.com/kaizhang/SciFlow.git
    commit:  f16e9ab5ce3abb37da259ab92d68cbf45020d241
    subdirs:
        - SciFlow
        - SciFlow-app
  - git:     https://github.com/haskell-distributed/distributed-process.git
    commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
  - distributed-process-monad-control-0.5.1.3
  - network-transport-tcp-0.7.0
  - distributed-static-0.3.9
  - jmacro-0.6.17

